### ISSUE TITLE
Version intl 0.18.0 incompatible

### ISSUE THREAD

**Issue by gabriel-translog** [sud0su/calendar_agenda#8]
Resolving dependencies...
Because every version of calendar_agenda depends on intl ^0.17.0 and translog_app depends on intl ^0.18.0, calendar_agenda is forbidden.
So, because tl_app depends on calendar_agenda ^0.0.2+3, version solving failed.
exit code 1

**Comment by dpiupy28352** [comment]
use this
```yaml
dependencies:
  calendar_agenda:
    git:
      url: https://github.com/Dough-su/calendar_agenda.git
```
